### ISSUE TITLE
Incorrect result of lodash.isEqual

### ISSUE THREAD

**Issue by aMarCruz** [loveencounterflow/jseq#4]
Hi @loveencounterflow , your work is amazing!

...but the result of "+0 should ne -0" for lodash seems incorrect in the [jsEq results](https://github.com/loveencounterflow/jseq#jseq).

I checked with this:

```js
const isEqual = require('lodash/isEqual')

const a = +0
const b = -0

console.log(isEqual(a, b))  // => true
```

Maybe I'm wrong, or its behavior was different in another version? I'm testing with lodash v4.17.11

Anyway, I've never seen an app where this difference represents a issue. Moreover, I believe that `+0 === -0 => true` is the expected result in the context of functional tests (should.js, chai, etc).

BTW: There's an interesting note in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Value_equality) regarding signed-zero equality in the new ECMA specs for `Set`.

**Comment by loveencounterflow** [comment]
Hi, thanks for your comment. I don't have time to look into this now, but I believe you're right: All said and done, the tendency for modern JS seems to be regarding plus and minus zero as equal. *Maybe* the lodash library made a switch here? 

For anyone planning to dive into the intricacies of JS equality, there's a new kid on the block, [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is). Turns out this function treats `NaN`s as equal, but `+0` and `-0` as not equal. So `Object.is(a,b)` is basically `a === b`, *except* for the treatment of `NaN` and signed zeros. Who on earth needed that and why?

[Quote](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Value_equality): "for Sets, +0 (which is strictly equal to -0) and -0 were different values. However, this was changed in the ECMAScript 2015 specification. [...] NaN is considered the same as NaN (even though NaN !== NaN)."

From this we can safely deduce that JS doesn't know either.

**Comment by aMarCruz** [comment]
@loveencounterflow your right, +0!==-0 was a bad decision and ES6 `Object.is` should have been designed with the SameValueZero algorithm, instead of SameValue.

I am currently writing a deep-comparison routine that uses SameValueZero. The existing ones are embedded in other tools, are very big, slow, or has not support for modern JS objects. I finished coding but I want to maintain a 100% coverage with as many tests as possible. Currently, it passes those of the lodash, underscore, and a few others. I will integrate some of yours before publishing it.

Thanks for your time and great work.
